// some random words
export default [
    'India',
    'America',
    'Malta',
    'Wallis and Futuna',
    'Grenada',
    'Pakistan',
    'China',
    'Japan',
    'NewZealand',
    'SriLanka',
    'Bangladesh',
    'Nepal',
    'HongKong',
    'Mexico',
    'Finland',
    'Germany',
    'Italy',
    'Prague',
    'Belgium',
    'Colombia',
    'Portugal',
    'Croatia',
    'Norway',
    'Poland',
    'Argentina',
  ];
  